/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */

import java.awt.*;
import java.security.AlgorithmConstraints;

import javax.swing.InternalFrameFocusTraversalPolicy;
import javax.swing.JColorChooser;

public class PaintApp extends javax.swing.JFrame {

    int old_mouse_x = 0;
    int old_mouse_y = 0;
    Color brushColor = Color.BLACK;
    Graphics2D graphics2d;
    int frist_mouse_x = 0;
    int frist_mouse_y = 0;

    /**
     * Creates new form PaintApp
     */
    public PaintApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton2.setText("Wyczyść");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
                old_mouse_x = 0;
                old_mouse_y = 0;
                frist_mouse_x = 0;
                frist_mouse_y = 0;
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 30, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Ołówek", "Linia", "Prostokąt", "Koło", "Wielokąt" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "1px", "2px", "3px", "4px", "5px", "6px", "7px" }));

        jButton1.setText("Kolor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(57, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1)
                                                .addComponent(jButton2)))
                                .addContainerGap(27, Short.MAX_VALUE)));

        jComboBox1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 360, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {
        //
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        brushColor = JColorChooser.showDialog(this, "WYbierz kolor", brushColor);
        jPanel1.setBackground(brushColor);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        Graphics g = jPanel3.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, jPanel3.getWidth(), jPanel3.getHeight());
    }

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {
        old_mouse_x = evt.getX();
        old_mouse_y = evt.getY();
    }

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {
        if (jComboBox1.getSelectedIndex() == 0) {
            graphics2d = (Graphics2D) jPanel3.getGraphics();
            if (graphics2d != null) {
                graphics2d.setColor(brushColor);
                graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));
                graphics2d.drawLine(old_mouse_x, old_mouse_y, evt.getX(), evt.getY());
            }
            old_mouse_x = evt.getX();
            old_mouse_y = evt.getY();
        }

    }

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {

        if (jComboBox1.getSelectedIndex() == 1) {
            graphics2d = (Graphics2D) jPanel3.getGraphics();
            if (graphics2d != null) {
                graphics2d.setColor(brushColor);
                graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));

                if (frist_mouse_x == 0 && frist_mouse_y == 0) {
                    frist_mouse_x = evt.getX();
                    frist_mouse_y = evt.getY();
                } else {
                    graphics2d.drawLine(frist_mouse_x, frist_mouse_y, evt.getX(), evt.getY());
                    frist_mouse_x = 0;
                    frist_mouse_y = 0;
                }

            }
        }

        if (jComboBox1.getSelectedIndex() == 2) {
            graphics2d = (Graphics2D) jPanel3.getGraphics();
            if (graphics2d != null) {
                graphics2d.setColor(brushColor);
                graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));

                if (frist_mouse_x == 0 && frist_mouse_y == 0) {
                    frist_mouse_x = evt.getX();
                    frist_mouse_y = evt.getY();
                } else {

                    if (frist_mouse_x > evt.getX() && frist_mouse_y > evt.getY()) {
                        graphics2d.drawRect(evt.getX(), evt.getY(), frist_mouse_x - evt.getX(),
                                frist_mouse_y - evt.getY());
                    } else if (frist_mouse_x < evt.getX() && frist_mouse_y < evt.getY()) {
                        graphics2d.drawRect(frist_mouse_x, frist_mouse_y, evt.getX() - frist_mouse_x,
                                evt.getY() - frist_mouse_y);
                    } else if (frist_mouse_x > evt.getX() && frist_mouse_y < evt.getY()) {
                        graphics2d.drawRect(evt.getX(), frist_mouse_y, frist_mouse_x - evt.getX(),
                                evt.getY() - frist_mouse_y);
                    } else if (frist_mouse_x < evt.getX() && frist_mouse_y > evt.getY()) {
                        graphics2d.drawRect(frist_mouse_x, evt.getY(), evt.getX() - frist_mouse_x,
                                frist_mouse_y - evt.getY());
                    }

                    frist_mouse_x = 0;
                    frist_mouse_y = 0;
                }
            }
        }

        if (jComboBox1.getSelectedIndex() == 3) {
            graphics2d = (Graphics2D) jPanel3.getGraphics();
            if (graphics2d != null) {
                graphics2d.setColor(brushColor);
                graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));

                if (frist_mouse_x == 0 && frist_mouse_y == 0) {
                    frist_mouse_x = evt.getX();
                    frist_mouse_y = evt.getY();
                } else {

                    if (frist_mouse_x > evt.getX() && frist_mouse_y > evt.getY()) {
                        graphics2d.drawOval(evt.getX(), evt.getY(), frist_mouse_x - evt.getX(),
                                frist_mouse_y - evt.getY());
                    } else if (frist_mouse_x < evt.getX() && frist_mouse_y < evt.getY()) {
                        graphics2d.drawOval(frist_mouse_x, frist_mouse_y, evt.getX() - frist_mouse_x,
                                evt.getY() - frist_mouse_y);
                    } else if (frist_mouse_x > evt.getX() && frist_mouse_y < evt.getY()) {
                        graphics2d.drawOval(evt.getX(), frist_mouse_y, frist_mouse_x - evt.getX(),
                                evt.getY() - frist_mouse_y);
                    } else if (frist_mouse_x < evt.getX() && frist_mouse_y > evt.getY()) {
                        graphics2d.drawOval(frist_mouse_x, evt.getY(), evt.getX() - frist_mouse_x,
                                frist_mouse_y - evt.getY());
                    }

                    frist_mouse_x = 0;
                    frist_mouse_y = 0;
                }
            }
        }

        if (jComboBox1.getSelectedIndex() == 4) {
            graphics2d = (Graphics2D) jPanel3.getGraphics();
            if (graphics2d != null) {
                graphics2d.setColor(brushColor);
                graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));

                // wielokąt
                if (frist_mouse_x == 0 && frist_mouse_y == 0) {
                    frist_mouse_x = evt.getX();
                    frist_mouse_y = evt.getY();
                } else {
                    graphics2d.drawLine(frist_mouse_x, frist_mouse_y, evt.getX(), evt.getY());

                    if (frist_mouse_x == evt.getX() && frist_mouse_y == evt.getY()) {
                        frist_mouse_x = 0;
                        frist_mouse_y = 0;
                        return;
                    }

                    frist_mouse_x = evt.getX();
                    frist_mouse_y = evt.getY();
                }

            }
        }
        // frist_mouse_x = evt.getX();
        // frist_mouse_y = evt.getY();

        // if (jComboBox1.getSelectedIndex() == 2) {
        // // narysuj prostokąt
        // graphics2d = (Graphics2D) jPanel3.getGraphics();
        // if (graphics2d != null) {
        // graphics2d.setColor(brushColor);
        // graphics2d.setStroke(new BasicStroke(jComboBox2.getSelectedIndex() + 1));
        // graphics2d.drawRect(old_mouse_x, old_mouse_y, evt.getX() - old_mouse_x,
        // evt.getY() - old_mouse_y);
        // }
        // old_mouse_x = evt.getX();
        // old_mouse_y = evt.getY();
        // }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
