/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import java.text.DecimalFormat;

/**
 *
 * @author mateu
 */
public class Calculator extends javax.swing.JFrame {

    String operation = "", operationBuffer = "";
    String previousEquation = "", actualEquation = "0";
    double result = 0;
    String answer = "";

    double numActualEquation;
    double numPreviousEquation;

    /**
     * Creates new form Cal
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldSCREEN = new javax.swing.JTextField();
        jButtonPLUS = new javax.swing.JButton();
        jButtonNUM5 = new javax.swing.JButton();
        jButtonMINUS = new javax.swing.JButton();
        jButtonNUM4 = new javax.swing.JButton();
        jButtonMULTIPLY = new javax.swing.JButton();
        jButtonNUM6 = new javax.swing.JButton();
        jButtonDIVIDE = new javax.swing.JButton();
        jButtonNUM7 = new javax.swing.JButton();
        jButtonISEQUALTO = new javax.swing.JButton();
        jButtonNUM8 = new javax.swing.JButton();
        jButtonDOT = new javax.swing.JButton();
        jButtonNUM9 = new javax.swing.JButton();
        jButtonPLUS_MINUS = new javax.swing.JButton();
        jButtonNUM0 = new javax.swing.JButton();
        jButtonAC = new javax.swing.JButton();
        jButtonNUM3 = new javax.swing.JButton();
        jButtonPROCENT = new javax.swing.JButton();
        jButtonNUM2 = new javax.swing.JButton();
        jButtonNUM1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextFieldSCREEN.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldSCREEN.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jTextFieldSCREEN.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSCREEN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSCREEN.setText("0");
        jTextFieldSCREEN.setBorder(null);
        jTextFieldSCREEN.setFocusable(false);
        jTextFieldSCREEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSCREENActionPerformed(evt);
            }
        });

        jButtonPLUS.setBackground(new java.awt.Color(255, 162, 31));
        jButtonPLUS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPLUS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPLUS.setText("+");
        jButtonPLUS.setBorderPainted(false);
        jButtonPLUS.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLUSActionPerformed(evt);
            }
        });

        jButtonNUM5.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM5.setText("5");
        jButtonNUM5.setBorderPainted(false);
        jButtonNUM5.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM5ActionPerformed(evt);
            }
        });

        jButtonMINUS.setBackground(new java.awt.Color(255, 162, 31));
        jButtonMINUS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMINUS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMINUS.setText("-");
        jButtonMINUS.setBorderPainted(false);
        jButtonMINUS.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMINUSActionPerformed(evt);
            }
        });

        jButtonNUM4.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM4.setText("4");
        jButtonNUM4.setBorderPainted(false);
        jButtonNUM4.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM4ActionPerformed(evt);
            }
        });

        jButtonMULTIPLY.setBackground(new java.awt.Color(255, 162, 31));
        jButtonMULTIPLY.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMULTIPLY.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMULTIPLY.setText("×");
        jButtonMULTIPLY.setBorderPainted(false);
        jButtonMULTIPLY.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonMULTIPLY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMULTIPLYActionPerformed(evt);
            }
        });

        jButtonNUM6.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM6.setText("6");
        jButtonNUM6.setBorderPainted(false);
        jButtonNUM6.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM6ActionPerformed(evt);
            }
        });

        jButtonDIVIDE.setBackground(new java.awt.Color(255, 162, 31));
        jButtonDIVIDE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonDIVIDE.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDIVIDE.setText("÷");
        jButtonDIVIDE.setBorderPainted(false);
        jButtonDIVIDE.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonDIVIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDIVIDEActionPerformed(evt);
            }
        });

        jButtonNUM7.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM7.setText("7");
        jButtonNUM7.setBorderPainted(false);
        jButtonNUM7.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM7ActionPerformed(evt);
            }
        });

        jButtonISEQUALTO.setBackground(new java.awt.Color(255, 162, 31));
        jButtonISEQUALTO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonISEQUALTO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonISEQUALTO.setText("=");
        jButtonISEQUALTO.setBorderPainted(false);
        jButtonISEQUALTO.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonISEQUALTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonISEQUALTOActionPerformed(evt);
            }
        });

        jButtonNUM8.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM8.setText("8");
        jButtonNUM8.setBorderPainted(false);
        jButtonNUM8.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM8ActionPerformed(evt);
            }
        });

        jButtonDOT.setBackground(new java.awt.Color(50, 50, 50));
        jButtonDOT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonDOT.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDOT.setText(".");
        jButtonDOT.setBorderPainted(false);
        jButtonDOT.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDOTActionPerformed(evt);
            }
        });

        jButtonNUM9.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM9.setText("9");
        jButtonNUM9.setBorderPainted(false);
        jButtonNUM9.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM9ActionPerformed(evt);
            }
        });

        jButtonPLUS_MINUS.setBackground(new java.awt.Color(168, 168, 168));
        jButtonPLUS_MINUS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPLUS_MINUS.setText("+/-");
        jButtonPLUS_MINUS.setBorderPainted(false);
        jButtonPLUS_MINUS.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonPLUS_MINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLUS_MINUSActionPerformed(evt);
            }
        });

        jButtonNUM0.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM0.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM0.setText("0");
        jButtonNUM0.setBorderPainted(false);
        jButtonNUM0.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM0ActionPerformed(evt);
            }
        });

        jButtonAC.setBackground(new java.awt.Color(168, 168, 168));
        jButtonAC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAC.setText("AC");
        jButtonAC.setBorderPainted(false);
        jButtonAC.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACActionPerformed(evt);
            }
        });

        jButtonNUM3.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM3.setText("3");
        jButtonNUM3.setBorderPainted(false);
        jButtonNUM3.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM3ActionPerformed(evt);
            }
        });

        jButtonPROCENT.setBackground(new java.awt.Color(168, 168, 168));
        jButtonPROCENT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPROCENT.setText("%");
        jButtonPROCENT.setBorderPainted(false);
        jButtonPROCENT.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonPROCENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPROCENTActionPerformed(evt);
            }
        });

        jButtonNUM2.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM2.setText("2");
        jButtonNUM2.setBorderPainted(false);
        jButtonNUM2.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM2ActionPerformed(evt);
            }
        });

        jButtonNUM1.setBackground(new java.awt.Color(50, 50, 50));
        jButtonNUM1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonNUM1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNUM1.setText("1");
        jButtonNUM1.setBorderPainted(false);
        jButtonNUM1.setPreferredSize(new java.awt.Dimension(80, 60));
        jButtonNUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUM1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(jButtonNUM4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNUM5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNUM6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonMINUS, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addComponent(jButtonNUM7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNUM8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonNUM9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonMULTIPLY, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButtonNUM1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonNUM2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonNUM3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonPLUS,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButtonAC,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonPLUS_MINUS,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonPROCENT,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonDIVIDE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jButtonNUM0,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                166,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonDOT,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButtonISEQUALTO,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldSCREEN, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldSCREEN, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonDIVIDE, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonPROCENT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonPLUS_MINUS, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonAC, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonMULTIPLY, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonMINUS, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonPLUS, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonISEQUALTO, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonDOT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNUM0, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // DODAWANIE LICZBY DO WYŚWIETLANIA
    public void addNumber(String number) {
        // 1 KROPKA DO WYŚWIETLANIA
        if (number.equals(".")) {
            if (actualEquation.contains(".")) {
                return;
            }
        }

        // +/- ZAMIANA ZNAKU LICZBY
        if (number.equals("+/-")) {
            if (actualEquation.contains("-")) {
                actualEquation = actualEquation.substring(1);
                updateResult();
                return;
            } else {
                if (actualEquation.equals("0") || actualEquation.equals("")) {
                    return;
                }
                actualEquation = "-" + actualEquation;
                updateResult();
                return;
            }
        }

        // LICZENIE PROCENTU
        if (number.equals("%")) {
            if (jTextFieldSCREEN.getText().endsWith(".")) {
                actualEquation = actualEquation.substring(0, actualEquation.length() - 1);
                formatResult(actualEquation);
                updateResult();
            }

            if (!operation.equals("")) {
                if (actualEquation.equals("") || actualEquation.equals("0")) {
                    return;
                }
                if (operation.equals("+")) {
                    actualEquation = String.valueOf(Double.parseDouble(actualEquation)
                            + Double.parseDouble(actualEquation) * Double.parseDouble(previousEquation) / 100);
                    formatResult(actualEquation);
                    updateResult();
                    return;
                }
                if (operation.equals("-")) {
                    actualEquation = String.valueOf(Double.parseDouble(actualEquation)
                            - Double.parseDouble(actualEquation) * Double.parseDouble(previousEquation) / 100);
                    formatResult(actualEquation);
                    updateResult();
                    return;
                }
                if (operation.equals("*")) {
                    actualEquation = String
                            .valueOf(Double.parseDouble(actualEquation) * Double.parseDouble(previousEquation) / 100);
                    formatResult(actualEquation);
                    updateResult();
                    return;
                }
                if (operation.equals("/")) {
                    actualEquation = String
                            .valueOf(Double.parseDouble(previousEquation) * 100 / Double.parseDouble(actualEquation));
                    formatResult(actualEquation);
                    updateResult();
                    return;
                }
            } else {
                if (actualEquation.equals("") || actualEquation.equals("0")) {
                    return;
                }
                actualEquation = String.valueOf(Double.parseDouble(actualEquation) / 100);
                formatResult(actualEquation);
                updateResult();
                return;
            }

        }

        // WYŚWIETLANIE MAX 10 CYFR
        if (actualEquation.length() == 10 && !actualEquation.contains(".")) {
            return;
        } else if (actualEquation.length() == 11 && actualEquation.contains(".")) {
            return;
        }

        // WYŚWIETLANIE LICZBY PRZY POCZĄTKOWYM 0 ORAZ KROPCE
        if (jTextFieldSCREEN.getText().equals("0")) {
            if (number.equals(".")) {
                actualEquation += number;
            } else {
                actualEquation = number;
            }
        } else {
            actualEquation += number;
        }

        updateResult();
    }

    // AKTUALIZACJA WYŚWIETLANIA
    private void updateResult() {
        System.out.println("actualEquation " + actualEquation);
        System.out.println("previousEquation " + previousEquation);
        System.out.println("operation " + operation);
        jTextFieldSCREEN.setText(actualEquation);
        answer = previousEquation + operation;
        System.out.println("answer " + answer);
    }

    // DODAWANIE OPERACJI DO LICZENIA
    public void doOperation(String operator) {
        // DYNAMICZNE ZMIENIANIE OPERACJI
        if (actualEquation.equals("") && !operator.equals("=")) {
            if (answer.length() > 0 && answer.substring(answer.length() - 1) != operator) {
                operation = operator;
            }
            System.out.println("LOL");
            return;
        }

        // LICZENIE
        if (!previousEquation.equals("")) {
            calculate();
        }

        // ZAPISYWANIE POPRZEDNIEJ OPERACJI
        // if (!operator.equals("=")) {
        operation = operator;
        previousEquation = actualEquation;
        updateResult();
        actualEquation = "";
        // }
    }

    // WYKONANIE DZIAŁANIA
    public void calculate() {
        try {
            if (actualEquation == "" && previousEquation == "") {
                return;
            }

            // System.out.println("Nie działa " + operation);
            numActualEquation = Double.parseDouble(actualEquation);
            numPreviousEquation = Double.parseDouble(previousEquation);
            // operationBuffer = operation;

            switch (operation) {
                case "+":
                    result = numPreviousEquation + numActualEquation;
                    break;
                case "-":
                    result = numPreviousEquation - numActualEquation;
                    break;
                case "*":
                    result = numPreviousEquation * numActualEquation;
                    break;
                case "/":
                    result = numPreviousEquation / numActualEquation;
                    break;
                default:
                    return;
            }

            // ERROR - DZIELENIE PRZEZ 0 - INFINITY
            if (Double.isInfinite(result)) {
                clearScreen();
                // addNumber("Error1");
                return;
            }

            actualEquation = Double.toString(result);
            formatResult(actualEquation);

            updateResult();
            operation = "";
        } catch (Exception e) {
            clearScreen();
            // addNumber("Error2");
        }
    }

    // FORMATOWANIE WYNIKU
    public void formatResult(String withDot) {
        Double withDotDouble = Double.parseDouble(withDot);

        DecimalFormat df = new DecimalFormat("#");
        df.setMaximumFractionDigits(9);
        actualEquation = df.format(withDotDouble);

        if ((actualEquation.length() > 10 && !actualEquation.contains(".") || actualEquation.length() > 11
                && actualEquation.contains("."))) {
            actualEquation = String.format("%.2E", withDotDouble);
        } else if (withDotDouble % 1 == 0) {
            actualEquation = String.format("%.0f", withDotDouble);
        } else {
            actualEquation = String.format("%.9f", withDotDouble);
            actualEquation = actualEquation.replaceAll("0*$", "");
        }
        actualEquation = actualEquation.replace(",", ".");
        if (actualEquation.endsWith(".")) {
            actualEquation = actualEquation.substring(0, actualEquation.length() - 1);
        }
    }

    // USUWANIE OSTATNIEGO ZNAKU
    public void deleteLast() {
        if (actualEquation.length() > 0) {
            actualEquation = actualEquation.substring(0, actualEquation.length() - 1);
            if (actualEquation.length() == 2 && actualEquation.contains("."))
                actualEquation = actualEquation.substring(0, actualEquation.length() - 1);

            updateResult();
        }

        if (actualEquation.length() == 0) {
            actualEquation = "0";
            updateResult();
        }
    }

    // WYCZYŚCZENIE EKRANU
    public void clearScreen() {
        actualEquation = "0";
        previousEquation = "";
        operation = "";
        operationBuffer = "";
        result = 0;
        updateResult();
    }

    private void jTextFieldSCREENActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSCREENActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldSCREENActionPerformed

    private void jButtonNUM0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM0ActionPerformed
        // TODO add your handling code here:
        addNumber("0");
    }// GEN-LAST:event_jButtonNUM0ActionPerformed

    private void jButtonNUM1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM1ActionPerformed
        // TODO add your handling code here:
        addNumber("1");
    }// GEN-LAST:event_jButtonNUM1ActionPerformed

    private void jButtonNUM2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM2ActionPerformed
        // TODO add your handling code here:
        addNumber("2");
    }// GEN-LAST:event_jButtonNUM2ActionPerformed

    private void jButtonNUM3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM3ActionPerformed
        // TODO add your handling code here:
        addNumber("3");
    }// GEN-LAST:event_jButtonNUM3ActionPerformed

    private void jButtonNUM4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM4ActionPerformed
        // TODO add your handling code here:
        addNumber("4");

    }// GEN-LAST:event_jButtonNUM4ActionPerformed

    private void jButtonNUM5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM5ActionPerformed
        // TODO add your handling code here:
        addNumber("5");

    }// GEN-LAST:event_jButtonNUM5ActionPerformed

    private void jButtonNUM6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM6ActionPerformed
        // TODO add your handling code here:
        addNumber("6");

    }// GEN-LAST:event_jButtonNUM6ActionPerformed

    private void jButtonNUM7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM7ActionPerformed
        // TODO add your handling code here:
        addNumber("7");

    }// GEN-LAST:event_jButtonNUM7ActionPerformed

    private void jButtonNUM8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM8ActionPerformed
        // TODO add your handling code here:
        addNumber("8");

    }// GEN-LAST:event_jButtonNUM8ActionPerformed

    private void jButtonNUM9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNUM9ActionPerformed
        // TODO add your handling code here:
        addNumber("9");

    }// GEN-LAST:event_jButtonNUM9ActionPerformed

    private void jButtonDOTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDOTActionPerformed
        // TODO add your handling code here:
        addNumber(".");

    }// GEN-LAST:event_jButtonDOTActionPerformed

    private void jButtonACActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonACActionPerformed
        // TODO add your handling code here:
        // deleteLast();
        clearScreen();

    }// GEN-LAST:event_jButtonACActionPerformed

    private void jButtonPLUS_MINUSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPLUS_MINUSActionPerformed
        // TODO add your handling code here:
        addNumber("+/-");

    }// GEN-LAST:event_jButtonPLUS_MINUSActionPerformed

    private void jButtonPROCENTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPROCENTActionPerformed
        // TODO add your handling code here:
        // doOperation("%");
        // procent z liczby wstaw do screen
        addNumber("%");
    }// GEN-LAST:event_jButtonPROCENTActionPerformed

    private void jButtonDIVIDEActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonDIVIDEActionPerformed
        // TODO add your handling code here:
        doOperation("/");

    }// GEN-LAST:event_jButtonDIVIDEActionPerformed

    private void jButtonMULTIPLYActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMULTIPLYActionPerformed
        // TODO add your handling code here:
        doOperation("*");

    }// GEN-LAST:event_jButtonMULTIPLYActionPerformed

    private void jButtonMINUSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonMINUSActionPerformed
        // TODO add your handling code here:
        doOperation("-");

    }// GEN-LAST:event_jButtonMINUSActionPerformed

    private void jButtonPLUSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPLUSActionPerformed
        // TODO add your handling code here:
        doOperation("+");
    }// GEN-LAST:event_jButtonPLUSActionPerformed

    private void jButtonISEQUALTOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        doOperation("=");
        // nie działa, po powturnym kliknięciu na = nie wyświetla wyniku - trzeba
        // przpisać opopwiednie wyniki do odpowiednich zmiennych
    }// GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAC;
    private javax.swing.JButton jButtonDIVIDE;
    private javax.swing.JButton jButtonDOT;
    private javax.swing.JButton jButtonISEQUALTO;
    private javax.swing.JButton jButtonMINUS;
    private javax.swing.JButton jButtonMULTIPLY;
    private javax.swing.JButton jButtonNUM0;
    private javax.swing.JButton jButtonNUM1;
    private javax.swing.JButton jButtonNUM2;
    private javax.swing.JButton jButtonNUM3;
    private javax.swing.JButton jButtonNUM4;
    private javax.swing.JButton jButtonNUM5;
    private javax.swing.JButton jButtonNUM6;
    private javax.swing.JButton jButtonNUM7;
    private javax.swing.JButton jButtonNUM8;
    private javax.swing.JButton jButtonNUM9;
    private javax.swing.JButton jButtonPLUS;
    private javax.swing.JButton jButtonPLUS_MINUS;
    private javax.swing.JButton jButtonPROCENT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldSCREEN;
    // End of variables declaration//GEN-END:variables
}
// GEN-END:variables
